name: redirect_platform_interface
description: >-
  A common platform interface for the redirect plugin.
  Used by platform-specific implementations to ensure a consistent API.
version: 0.1.0+1
repository: https://github.com/Bdaya-Dev/redirect/tree/main/packages/redirect_platform_interface
topics:
  - redirect
  - platform-interface

resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  redirect_core: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.1.0
