name: redirect
description: A Flutter plugin to facilitate redirect-based flows, e.g. OIDC authorization code grant or URL-based payment gateways
version: 0.1.0+1

resolution: workspace

environment:
  sdk: ^3.9.0

flutter:
  plugin:
    platforms:
      android:
        default_package: redirect_android
      ios:
        default_package: redirect_darwin
      linux:
        default_package: redirect_desktop
      macos:
        default_package: redirect_darwin
      web:
        default_package: redirect_web
      windows:
        default_package: redirect_desktop

dependencies:
  flutter:
    sdk: flutter
  redirect_android: ^0.1.0
  redirect_darwin: ^0.1.0
  redirect_desktop: ^0.1.0
  redirect_platform_interface: ^0.1.0
  redirect_web: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.0.0
