name: redirect_cli

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/redirect_cli.yaml"
      - "packages/redirect_cli/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/redirect_cli.yaml"
      - "packages/redirect_cli/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      dart_sdk: stable
      working_directory: packages/redirect_cli

  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
    with:
      working_directory: packages/redirect_cli
