name: redirect_android

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/redirect_android.yaml"
      - "packages/redirect_android/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/redirect_android.yaml"
      - "packages/redirect_android/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      working_directory: packages/redirect_android
      min_coverage: 0
      coverage_excludes: "**/*.g.dart"

